name: Build and Release APK

# URUCHAMIAJ WORKFLOW TYLKO PO WYPCHNIĘCIU TAGA
on:
  push:
    tags:
      - 'v*.*.*' # np. v1.0.0, v1.2.3

jobs:
  build-and-release:
    runs-on: ubuntu-latest
    steps:
      # POBIERZ KOD Z CAŁĄ HISTORIĄ TAGÓW
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0 

      # Reszta kroków (Cache, Set up JDK, Build APK) pozostaje bez zmian...
      - name: Cache Gradle dependencies
        uses: actions/cache@v4
        with:
          path: |
            ~/.gradle/caches
            ~/.gradle/wrapper
          key: ${{ runner.os }}-gradle-${{ hashFiles('**/*.gradle*', '**/gradle-wrapper.properties') }}

      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          java-version: '17'
          distribution: 'temurin'

      - name: Build and Sign APK
        env:
          SIGNING_KEY_BASE64: ${{ secrets.SIGNING_KEY_BASE64 }}
          ALIAS: ${{ secrets.ALIAS }}
          KEY_STORE_PASSWORD: ${{ secrets.KEY_STORE_PASSWORD }}
          KEY_PASSWORD: ${{ secrets.KEY_PASSWORD }}
        run: |
          echo $SIGNING_KEY_BASE64 | base64 --decode > release.jks
          chmod +x ./gradlew
          ./gradlew assembleRelease -Psigning.keyStore.file=$(pwd)/release.jks

      - name: Create GitHub Release
        uses: softprops/action-gh-release@v2
        with:
          repository: MacPal2002/ans-nt-app_release
          token: ${{ secrets.RELEASE_PAT }}
          tag_name: ${{ github.ref_name }}
          name: Release ${{ github.ref_name }}
          files: app/build/outputs/apk/release/app-${{ github.ref_name }}.apk
          draft: false
          prerelease: false
