name: Build and Release APK

on:
  push:
    tags:
      - 'v*.*.*' # np. v1.0.0, v1.2.3

jobs:
  build-and-release:
    runs-on: ubuntu-latest
    steps:
      # POBIERZ KOD Z CAŁĄ HISTORIĄ TAGÓW
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
          
      - name: Generate google-services.json
        run: |
          mkdir -p app/src/debug
          mkdir -p app/src/release

          cat > app/src/debug/google-services.json <<EOF
          {
            "project_info": {
              "project_number": "829995078625",
              "project_id": "test-f856b",
              "storage_bucket": "test-f856b.firebasestorage.app"
            },
            "client": [
              {
                "client_info": {
                  "mobilesdk_app_id": "1:829995078625:android:4d99ee10ddcf526d6278a0",
                  "android_client_info": {
                    "package_name": "com.example.test1"
                  }
                },
                "oauth_client": [],
                "api_key": [
                  {
                    "current_key": "${FIREBASE_API_KEY}"
                  }
                ],
                "services": {
                  "appinvite_service": {
                    "other_platform_oauth_client": []
                  }
                }
              }
            ],
            "configuration_version": "1"
          }
          EOF

          # Kopia dla release:
          cp app/src/debug/google-services.json app/src/release/google-services.json
        env:
          FIREBASE_API_KEY: ${{ secrets.FIREBASE_API_KEY }}


      - name: Cache Gradle dependencies
        uses: actions/cache@v4
        with:
          path: |
            ~/.gradle/caches
            ~/.gradle/wrapper
          key: ${{ runner.os }}-gradle-${{ hashFiles('**/*.gradle*', '**/gradle-wrapper.properties') }}

      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          java-version: '17'
          distribution: 'temurin'

      - name: Build and Sign APK
        env:
          SIGNING_KEY_BASE64: ${{ secrets.SIGNING_KEY_BASE64 }}
          ALIAS: ${{ secrets.ALIAS }}
          KEY_STORE_PASSWORD: ${{ secrets.KEY_STORE_PASSWORD }}
          KEY_PASSWORD: ${{ secrets.KEY_PASSWORD }}
        run: |
          echo $SIGNING_KEY_BASE64 | base64 --decode > release.jks
          chmod +x ./gradlew
          ./gradlew assembleRelease -Psigning.keyStore.file=$(pwd)/release.jks

      - name: Create GitHub Release
        uses: softprops/action-gh-release@v2
        with:
          repository: MacPal2002/ans-nt-app_release
          token: ${{ secrets.RELEASE_PAT }}
          tag_name: ${{ github.ref_name }}
          name: Release ${{ github.ref_name }}
          files: app/build/outputs/apk/release/app-${{ github.ref_name }}.apk
          draft: false
          prerelease: false
